//
//  InfoGodsVC.swift
import Foundation
import UIKit

class InfoGodsVC: UIViewController {
    
    var selectCount: Int = 0 {
        didSet {
        updateInfo()
        }
    }
    
    
    private var contentView: InfoGodsView {
        view as? InfoGodsView ?? InfoGodsView()
    }
    
    override func loadView() {
        view = InfoGodsView()
        
    }
    override func viewDidLoad() {
        super.viewDidLoad()
        selectBtn()
    }
    
    private func selectBtn() {
        contentView.backBtn.addTarget(self, action: #selector(back), for: .touchUpInside)
        contentView.quizBtn.addTarget(self, action: #selector(quizViewTapped), for: .touchUpInside)

    }

    @objc private func back() {
        navigationController?.popViewController(animated: true)
    }
    
    @objc private func quizViewTapped() {
       
        let quizVC = InfoQuizVC(godsIndex: selectCount)
        navigationController?.pushViewController(quizVC, animated: false)
    }
    
    private let imageCell: [UIImage] = [.imgGodsOne, .imgGodsTwo, .imgGodsThree, .imgGodsFour, .imgGodsFive, .imgGodsSix, .imgGodsSeven, .imgGodsEight, .imgGodsNine, .imgGodsTen]

    private func updateInfo() {
        switch selectCount {
        case 0:
            contentView.centerImage.image = .imgGodsOne
            contentView.bodyFieldInfo.text  = """
    Ra, also spelled Re, is one of the most important deities in ancient Egyptian religion, worshipped as the god of the sun, creation, and kingship. He is often depicted as a man with the head of a falcon, crowned with a solar disk surrounded by a serpent. This image underscores his role as the sun god, embodying light, warmth, and growth.
    The mythology of Ra begins with his role as the creator of the world. According to the Heliopolitan cosmology, Ra emerged from the primordial waters of Nun as a benben stone or as an infant, creating himself. He then produced Shu, the god of air, and Tefnut, the goddess of moisture. From these deities came Geb (earth) and Nut (sky), who in turn gave birth to Osiris, Isis, Set, and Nephthys. Thus, Ra was seen as the progenitor of the gods and all life on earth.
    Ra's daily journey across the sky in his solar barque (boat) symbolized the sun's passage from dawn to dusk. During the day, he traveled in the barque known as Mandjet, which sailed across the sky from east to west. As night fell, Ra was believed to enter the underworld, or Duat, where he transformed into his ram-headed form, Atum-Ra. Here, he traveled through the 12 regions of Duat, each representing an hour of the night, on the barque known as Mesektet. This journey was perilous, involving battles with the serpent Apophis, who represented chaos and tried to prevent Ra from bringing light to the world each dawn. The victory of Ra over Apophis every night was seen as the triumph of order over chaos, ensuring the sun would rise again.
    Ra's influence extended beyond mythology into the realm of kingship. The pharaohs were considered the "sons of Ra," serving as his earthly representatives. This divine connection granted the pharaohs authority and legitimacy, positioning them as intermediaries between the gods and the people. Temples dedicated to Ra, such as the sun temple at Heliopolis, became centers of worship and political power. The obelisks, symbols of Ra's rays, were often erected at these sites, emphasizing the connection between the god and the pharaohs.
    The worship of Ra evolved over time, especially during the Middle Kingdom and New Kingdom periods. He was often merged with other deities, creating syncretic gods such as Amun-Ra and Atum-Ra. Amun-Ra became particularly significant in Thebes, where the temple complex at Karnak was dedicated to him. This fusion reinforced Ra's position as the supreme god while allowing local traditions and beliefs to integrate seamlessly into the broader religious landscape.
    Ra's legacy is evident in numerous artifacts, texts, and architectural wonders that have survived millennia. The Pyramid Texts, Coffin Texts, and the Book of the Dead all include hymns and spells invoking Ra, illustrating his central role in Egyptian cosmology and afterlife beliefs. These texts reveal the intricate theology surrounding Ra, detailing his attributes, myths, and the rituals performed in his honor.
    The artistic representations of Ra evolved, reflecting changes in religious and cultural contexts. Initially depicted as a falcon-headed man, Ra's iconography expanded to include the sun disk encircled by a cobra (Uraeus), symbolizing royal authority and divine protection. This imagery was often incorporated into the regalia of the pharaohs, reinforcing their divine right to rule.
    Ra's worship persisted for thousands of years, adapting to changes in political and religious landscapes. Even as the prominence of other deities like Osiris and Isis grew, Ra remained a cornerstone of Egyptian spirituality. His enduring legacy is a testament to his profound impact on ancient Egyptian religion and culture.
"""
        case 1:
            contentView.centerImage.image = .imgGodsTwo
            contentView.bodyFieldInfo.text  = """
Osiris, one of the most significant deities in ancient Egyptian mythology, was revered as the god of the afterlife, resurrection, and fertility. His myth and cult had a profound impact on Egyptian religion and culture, spanning over millennia. Osiris is often depicted as a green-skinned man with a pharaoh's beard, partially wrapped as a mummy, holding a crook and flail, symbols of kingship and power.
Osiris's origins are rooted in the ancient Egyptian belief in the cyclical nature of life, death, and rebirth. According to myth, Osiris was the firstborn son of the earth god Geb and the sky goddess Nut. He was married to his sister Isis, and they had a son named Horus. Osiris was a benevolent and just ruler of Egypt, credited with teaching humanity agriculture, laws, and the arts of civilization.
However, Osiris's reign was cut short by his jealous brother Set, who coveted the throne. Set devised a plot to kill Osiris by tricking him into lying in a beautifully crafted coffin, which Set then sealed and threw into the Nile River. The coffin eventually washed ashore at Byblos, where a tamarisk tree grew around it. Isis, heartbroken by her husband's death, searched tirelessly for Osiris's body. When she found the coffin, she brought it back to Egypt, but Set discovered it and, in a fit of rage, dismembered Osiris into 14 pieces, scattering them across Egypt.
Isis, with the help of her sister Nephthys, Anubis, and Thoth, retrieved and reassembled Osiris's body, using her magical abilities to breathe life back into him. This act of resurrection established Osiris as the god of the afterlife, overseeing the judgment of souls and granting eternal life to the righteous. Osiris's resurrection symbolized the eternal cycle of life and death, a central tenet in Egyptian belief.
The myth of Osiris also introduced the concept of the judgment of the dead. In the Hall of Ma'at, the deceased's heart was weighed against the feather of Ma'at, the goddess of truth and justice. If the heart was found lighter than the feather, the soul was deemed pure and allowed to enter the afterlife, joining Osiris in the Field of Reeds, a paradise. If the heart was heavier, it was devoured by Ammit, a fearsome creature with the head of a crocodile, the body of a lion, and the hindquarters of a hippopotamus.
The cult of Osiris was one of the most widespread in ancient Egypt, with major centers of worship in Abydos and Philae. Annual festivals celebrated his death and resurrection, including the "Passion of Osiris," a dramatic reenactment of his myth, which involved rituals of mourning and jubilation, symbolizing the promise of rebirth and eternal life. These ceremonies reinforced the Egyptian belief in the afterlife and the hope for immortality.
Osiris's influence extended beyond religious practices into the realm of pharaonic authority. The pharaohs identified themselves with Horus during their lives and with Osiris in death, underscoring their divine right to rule and their hope for eternal life. This association strengthened the pharaoh's role as both a temporal and spiritual leader, bridging the mortal and divine realms.
Osiris's iconography evolved over time, but he consistently retained his mummy-like appearance, signifying his connection to the afterlife and resurrection. The crook and flail, traditional symbols of Egyptian kingship, emphasized his authority and protection. His green skin symbolized rebirth, vegetation, and fertility, further reinforcing his role as a god of life and renewal.
In summary, Osiris's myth and worship were central to ancient Egyptian religion, reflecting the civilization's deep-seated beliefs in the afterlife, resurrection, and the cyclical nature of existence. His enduring legacy is evident in the numerous texts, monuments, and rituals that celebrated his divine role, influencing not only Egyptian culture but also the broader Mediterranean world.
"""
        case 2:
            contentView.centerImage.image = .imgGodsThree
            contentView.bodyFieldInfo.text  =  """
Isis, one of the most venerated goddesses in ancient Egyptian mythology, is revered as the goddess of magic, motherhood, and fertility. Often depicted as a woman with a throne-shaped crown or a solar disk between cow horns, Isis embodies the ideals of maternal devotion, healing, and protection. Her widespread worship extended far beyond Egypt, influencing numerous cultures around the Mediterranean.
Isis's mythology is intricately linked with that of her husband, Osiris, and their son, Horus. As the sister and wife of Osiris, Isis played a crucial role in his myth of death and resurrection. When Osiris was murdered and dismembered by Set, Isis's unwavering devotion and magical prowess were pivotal in his resurrection. With the help of her sister Nephthys, Thoth, and Anubis, Isis located and reassembled Osiris's body, using her formidable magical abilities to restore him to life. This act not only solidified her status as a powerful sorceress but also as a symbol of eternal love and fidelity.
Isis's maternal aspect is most prominently displayed in her role as the mother of Horus. After reviving Osiris, she conceived Horus, whom she raised in secrecy to protect him from Set's wrath. Her nurturing and protective nature ensured Horus's survival and eventual victory over Set, restoring order to Egypt. This narrative emphasized Isis's role as a protector of children and the vulnerable, earning her a special place in the hearts of the ancient Egyptians.
The worship of Isis was deeply embedded in Egyptian society. Temples dedicated to her, such as those at Philae and Dendera, were centers of pilgrimage and devotion. Her priests and priestesses performed rituals that invoked her healing powers, sought her protection, and honored her maternal qualities. Isis was often invoked in spells and amulets, believed to offer protection and blessings to the wearer. Her headdress, combining the throne and solar disk, symbolized her authority and connection to both the earthly realm and the divine.
Isis's influence extended beyond the borders of Egypt. During the Hellenistic period, her cult spread throughout the Mediterranean, blending with local traditions and deities. The Greeks and Romans adopted her worship, integrating her into their own pantheons. In Roman times, the cult of Isis became one of the most prominent mystery religions, attracting followers with its promises of salvation, eternal life, and personal connection to the divine.
The rituals and festivals dedicated to Isis were elaborate and imbued with symbolic meaning. The "Feast of the Lights" celebrated her role in bringing light and life, while the "Navigium Isidis" marked the beginning of the sailing season, invoking her protection for sailors. These ceremonies reinforced her multifaceted nature as a goddess of the home, fertility, and the cosmos.
Isis's legacy is evident in the rich tapestry of art, literature, and religious practices that celebrated her. She was often depicted nursing Horus, symbolizing her nurturing aspect, or with wings spread wide, representing her protective powers. Texts such as the "Isis aretalogies" extolled her virtues and miracles, affirming her status as a universal goddess.
In summary, Isis's enduring appeal lies in her embodiment of the fundamental aspects of life and death, love and loss, protection and power. Her mythology and worship reflect the ancient Egyptians' deep-seated beliefs in the cyclical nature of existence, the power of magic, and the sanctity of motherhood. As one of the most beloved deities in the ancient world, Isis's influence transcended cultural and temporal boundaries, leaving an indelible mark on the spiritual landscape of the Mediterranean and beyond.
"""
            
        case 3:
            contentView.centerImage.image = .imgGodsFour
            contentView.bodyFieldInfo.text  =  """
 Horus, one of the most significant deities in ancient Egyptian mythology, was revered as the god of the sky, kingship, and protection. Often depicted as a falcon or a man with the head of a falcon, Horus embodied the ideals of divine kingship and the protector of the pharaohs. His mythology and worship were central to Egyptian religion, reflecting the civilization's beliefs in the divine right of kings and the eternal struggle between order and chaos.
The mythology of Horus is deeply intertwined with that of his parents, Osiris and Isis, and his uncle Set. After Osiris was murdered by Set, Isis conceived Horus in secret and raised him in the marshes of the Nile Delta to protect him from Set's wrath. As he grew, Horus became determined to avenge his father's death and reclaim the throne of Egypt from Set. This epic conflict between Horus and Set is one of the most important narratives in Egyptian mythology, symbolizing the struggle between order (ma'at) and chaos (isfet).
Horus's battle with Set was not just physical but also involved a series of trials and legal disputes before the gods. The resolution of this conflict, often depicted in temple reliefs and texts, culminated in Horus being recognized as the rightful heir to Osiris and the legitimate ruler of Egypt. This victory established Horus as the symbol of divine kingship and protector of the pharaohs, who were seen as his earthly incarnations.
Horus's association with the sky is reflected in his name, which means "the distant one" or "he who is above." As the sky god, Horus was believed to have his right eye as the sun and his left eye as the moon. This duality symbolized the balance between day and night, light and darkness. The "Eye of Horus" (Wedjat), a powerful symbol of protection, healing, and restoration, became one of the most important amulets in ancient Egypt, believed to ward off evil and promote health and well-being.
The worship of Horus was widespread throughout Egypt, with major cult centers at Nekhen (Hierakonpolis) and Edfu. At Edfu, the Temple of Horus, one of the best-preserved temples in Egypt, stands as a testament to his enduring significance. This temple, built during the Ptolemaic period, was the site of annual festivals reenacting the myth of Horus's victory over Set, emphasizing the themes of renewal and the triumph of order over chaos.
Horus's role as the protector of the pharaohs was central to Egyptian state ideology. The pharaohs, considered the "Living Horus," embodied his divine authority and were often depicted wearing the "Horus falcon" crown, symbolizing their role as Horus's earthly representatives. This divine connection legitimized the pharaoh's rule, reinforcing the notion of the pharaoh as the intermediary between the gods and the people.
Horus's iconography evolved over time, reflecting his multifaceted nature. Initially depicted as a falcon or a man with a falcon's head, Horus was also portrayed as a child (Horus the Younger) with a sidelock of youth, seated on his mother's lap. This image emphasized his role as the divine child and the heir to Osiris. Additionally, Horus was sometimes depicted as a sphinx, combining the attributes of a lion and a falcon, symbolizing his power and protective nature.
The influence of Horus extended beyond religion into art, literature, and statecraft. His mythology inspired numerous texts, including the "Contendings of Horus and Set," which detailed his struggles and ultimate victory. The "Eye of Horus" symbol permeated Egyptian art and architecture, often appearing on tombs, temples, and everyday objects, reflecting its importance in ensuring protection and prosperity.
In summary, Horus's mythology and worship were central to ancient Egyptian religion, symbolizing the ideals of kingship, protection, and the eternal struggle between order and chaos. His enduring legacy is evident in the numerous texts, monuments, and rituals that celebrated his divine role, influencing not only Egyptian culture but also the broader Mediterranean world.
"""

        case 4:
            contentView.centerImage.image = .imgGodsFive
            contentView.bodyFieldInfo.text  =  """
Anubis, one of the most ancient and significant deities in Egyptian mythology, is primarily associated with mummification and the afterlife. Often depicted as a man with the head of a jackal or as a black jackal, Anubis embodies the connection between the living and the dead. His role in guiding souls to the afterlife and overseeing the embalming process made him a key figure in Egyptian funerary practices.
Anubis's origins trace back to the early periods of Egyptian history, predating the rise of Osiris as the chief deity of the afterlife. Initially, Anubis was the primary god of the dead, responsible for overseeing the mummification process and protecting the deceased in their journey to the afterlife. As Osiris's cult gained prominence, Anubis's role shifted, but he remained integral to funerary rites and rituals.
In Egyptian mythology, Anubis is the son of Osiris and Nephthys. His birth is shrouded in secrecy, as Nephthys, unable to care for him, left him in the care of Isis, Osiris's wife. Isis raised Anubis, and he became a loyal guardian of the dead and a protector of Osiris. Anubis played a crucial role in the resurrection of Osiris, assisting Isis in the embalming and reassembly of Osiris's body, thus cementing his association with mummification and the afterlife.
One of the most iconic aspects of Anubis's mythology is his role in the "Weighing of the Heart" ceremony, a central tenet of Egyptian belief in the afterlife. In this ceremony, the heart of the deceased was weighed against the feather of Ma'at, the goddess of truth and justice. Anubis presided over this judgment, ensuring the scales were balanced and fair. If the heart was lighter than the feather, the soul was deemed pure and allowed to enter the Field of Reeds, an eternal paradise. If the heart was heavier, it was devoured by Ammit, a fearsome creature, condemning the soul to oblivion.
The worship of Anubis was widespread, with numerous temples and shrines dedicated to him throughout Egypt. His priests and priestesses played a vital role in the embalming process, performing rituals and spells to protect and preserve the deceased for their journey to the afterlife. Anubis was often invoked in funerary texts, such as the Pyramid Texts, Coffin Texts, and the Book of the Dead, which included prayers and spells to ensure safe passage to the afterlife.
Anubis's iconography is rich and symbolic. The jackal, often associated with cemeteries and tombs, was chosen as his animal form due to its nocturnal habits and scavenging behavior, symbolizing protection against grave robbers and the purification of the deceased. His black color, representing the color of mummified flesh and the fertile soil of the Nile, further emphasized his connection to death and rebirth.
Anubis's influence extended beyond religion into the realms of art, literature, and popular culture. He is frequently depicted in tomb paintings, sarcophagi, and amulets, underscoring his protective and guiding role. His imagery also appears in modern interpretations of Egyptian mythology, reflecting his enduring legacy as a symbol of the afterlife and the mysteries of death.
In summary, Anubis's mythology and worship reflect the ancient Egyptians' profound reverence for the afterlife and the elaborate rituals surrounding death and burial. His role as the god of mummification and protector of the dead highlights the civilization's beliefs in the cyclical nature of life and death, the importance of funerary practices, and the hope for eternal life.
"""

        case 5:
            contentView.centerImage.image = .imgGodsSix
            contentView.bodyFieldInfo.text  = """
Set, also known as Seth or Setekh, is one of the most complex and multifaceted deities in ancient Egyptian mythology. Revered as the god of chaos, storms, deserts, and war, Set's character embodies the dual nature of destruction and protection. Often depicted as a man with the head of a mysterious creature known as the "Set animal," which has a long, curved snout and erect, square-tipped ears, Set's imagery reflects his unique and ambiguous nature.
Set's mythology is primarily defined by his conflict with his brother Osiris and nephew Horus. According to the myth, Set, driven by jealousy and a desire for power, murdered his brother Osiris to usurp the throne of Egypt. He tricked Osiris into lying in a beautifully crafted coffin, which he then sealed and cast into the Nile River. This act of fratricide plunged Egypt into chaos and darkness, symbolizing Set's association with disorder and evil.
After murdering Osiris, Set dismembered his body and scattered the pieces across Egypt. Isis, Osiris's wife, and Nephthys, Set's wife, along with Anubis and Thoth, searched for and reassembled Osiris's body, allowing Isis to revive him temporarily through her magical abilities. Osiris's resurrection, however, was incomplete, and he became the ruler of the underworld, leaving the earthly throne contested between Set and Horus, the son of Osiris.
The battle between Set and Horus for the throne of Egypt is one of the most significant narratives in Egyptian mythology. This epic conflict, known as the "Contendings of Horus and Set," involved a series of physical and magical battles, legal disputes, and trials before the gods. The resolution of this conflict saw Horus emerge victorious, reclaiming the throne and restoring order to Egypt. Set, although defeated, was not entirely vilified; in some versions of the myth, he was integrated into the pantheon as a necessary force of chaos that balanced Ma'at, the principle of order and justice.
Set's dual nature is further exemplified by his role as a protector of Ra, the sun god. During Ra's nightly journey through the underworld, Set stood at the prow of Ra's solar barque, defending it from the serpent Apophis, a symbol of chaos and darkness. This aspect of Set's mythology underscores his complexity, portraying him as both a destroyer and a defender of order.
The worship of Set varied significantly over time and across different regions of Egypt. In some periods, particularly during the Second Intermediate Period and the early New Kingdom, Set was revered as a powerful and protective deity. His cult center was located at Ombos (Naqada), where he was worshipped alongside his consort Nephthys and other local deities. However, during the later periods, especially after the unification of Upper and Lower Egypt, Set's reputation deteriorated, and he became associated with foreign invaders and perceived as an antagonist to the principle of Ma'at.
Despite his negative aspects, Set's influence and worship persisted, reflecting the Egyptian belief in the necessity of balance between order and chaos. His imagery, often depicted on amulets, temple reliefs, and in funerary texts, emphasized his protective attributes, particularly in defending the sun god Ra from the forces of darkness. The "Set animal," unique to Set's iconography, symbolizes his enigmatic and multifaceted nature, blending elements of various animals to create a distinctive representation of his divine power.
Set's legacy extends beyond the confines of ancient Egyptian religion, influencing later cultures and mythologies. His character as a god of chaos and storms finds parallels in other mythological traditions, highlighting the universal themes of conflict, balance, and the duality of creation and destruction.
In summary, Set's mythology and worship illustrate the complexity of ancient Egyptian beliefs in the interplay of order and chaos. His role as both a destroyer and protector underscores the civilization's understanding of the necessity of balance in the cosmos. Set's enduring presence in Egyptian mythology and his multifaceted nature reflect the richness and depth of one of the world's oldest religious traditions.
"""

        case 6:
            contentView.centerImage.image = .imgGodsSeven
            contentView.bodyFieldInfo.text  = """
Thoth, known as the god of wisdom, writing, and magic, is one of the most important and revered deities in ancient Egyptian mythology. Often depicted as a man with the head of an ibis or a baboon, Thoth embodies the principles of knowledge, communication, and the divine scribe. His mythology and worship highlight the ancient Egyptians' reverence for learning, record-keeping, and the esoteric arts.
Thoth's origins are rooted in the earliest periods of Egyptian history, where he was associated with the moon and the measurement of time. His lunar aspect is reflected in his role as the regulator of time, the creator of the calendar, and the recorder of the passage of days. Thoth's connection to the moon also emphasizes his association with the cycles of nature, balance, and the cosmic order.
As the divine scribe, Thoth was believed to have invented writing and hieroglyphs, enabling the recording of knowledge, religious texts, and historical events. This invention was crucial for the administration of the state, the practice of religion, and the preservation of culture. Thoth's role as the patron of scribes and scholars made him a central figure in the intellectual life of ancient Egypt. He was often depicted holding a writing palette and stylus, symbolizing his authority over written knowledge and communication.
Thoth's wisdom and intellect are further exemplified by his role as a mediator and counselor among the gods. In the myth of Osiris, Thoth assisted Isis and Anubis in the resurrection of Osiris, using his magical abilities and vast knowledge to guide and protect them. He also played a key role in the judgment of the dead, recording the outcome of the "Weighing of the Heart" ceremony, where the deceased's heart was weighed against the feather of Ma'at.
The mythology of Thoth includes his role in the creation and maintenance of the universe. According to some traditions, Thoth was the creator of the Ogdoad, a group of eight primordial deities representing the elements of chaos before creation. He is also credited with maintaining the balance of the cosmos through his knowledge of divine laws and magical spells. Thoth's connection to Ma'at, the goddess of truth and justice, underscores his role in upholding the principles of order and harmony in the universe.
The worship of Thoth was widespread, with major cult centers at Hermopolis (Khemenu) and other significant sites throughout Egypt. His temples were centers of learning and scholarship, where priests and scribes studied sacred texts, astronomy, mathematics, and magic. The "House of Life" (Per Ankh), associated with Thoth, served as a repository of knowledge and a training ground for scribes and scholars.
Thoth's influence extended beyond Egypt, impacting other cultures and religions. In Greek mythology, he was identified with Hermes, the messenger of the gods, and was revered as Hermes Trismegistus, a figure associated with alchemy, astrology, and esoteric wisdom. The Hermetic tradition, which emerged from this syncretism, emphasized the pursuit of spiritual knowledge and the understanding of the mysteries of the universe.
Thoth's iconography is rich and varied, reflecting his multifaceted nature. The ibis, his sacred bird, symbolizes wisdom, precision, and the connection between the earthly and divine realms. The baboon, another of his animal forms, represents intelligence, reflection, and the ability to see both the physical and spiritual worlds. These symbols appear frequently in Egyptian art, emphasizing Thoth's role as a mediator between the gods and humanity.
In summary, Thoth's mythology and worship highlight the ancient Egyptians' profound respect for knowledge, wisdom, and the written word. His role as the divine scribe, mediator, and upholder of cosmic order underscores the civilization's emphasis on the importance of balance, justice, and intellectual pursuits. Thoth's enduring legacy continues to influence modern interpretations of Egyptian mythology and esoteric traditions.
"""
        case 7:
            contentView.centerImage.image = .imgGodsEight
            contentView.bodyFieldInfo.text  = """
Ma'at, one of the most essential and revered deities in ancient Egyptian mythology, embodies the concepts of truth, justice, and cosmic order. Often depicted as a woman with an ostrich feather on her head, Ma'at represents the fundamental principles that governed both the universe and human society. Her mythology and worship highlight the ancient Egyptians' deep-seated beliefs in balance, harmony, and ethical conduct.
Ma'at's origins are rooted in the earliest periods of Egyptian history, where she was seen as the personification of the laws that maintained the universe. The concept of Ma'at was integral to the Egyptians' understanding of the world, influencing their religion, politics, and daily life. Ma'at was not just a goddess but also a guiding principle, representing the ideal state of the world, where everything was in balance and functioning as it should.
In Egyptian mythology, Ma'at is often associated with the sun god Ra, serving as his constant companion and advisor. She accompanied Ra on his daily journey across the sky, ensuring that his path remained true and unimpeded by the forces of chaos. This relationship underscores Ma'at's role in maintaining the cosmic order and the regularity of natural phenomena, such as the rising and setting of the sun.
One of the most significant aspects of Ma'at's mythology is her role in the "Weighing of the Heart" ceremony in the afterlife. In this ritual, the heart of the deceased was weighed against the feather of Ma'at. If the heart was lighter than the feather, it indicated that the person had lived a life in accordance with Ma'at's principles, and they were granted access to the Field of Reeds, an eternal paradise. If the heart was heavier, it was devoured by Ammit, condemning the soul to oblivion. This ceremony emphasized the importance of living a virtuous and balanced life, adhering to the principles of truth and justice.
The worship of Ma'at was widespread, with temples and shrines dedicated to her throughout Egypt. Her priests and priestesses played a vital role in upholding the principles of Ma'at, ensuring that laws were just and that the community adhered to ethical standards. The pharaohs, as the earthly representatives of Ma'at, were expected to rule in accordance with her principles, maintaining order and justice in the land. This concept, known as "Ma'at," was central to the legitimacy of their rule.
Ma'at's influence extended beyond the realm of religion into the daily lives of the ancient Egyptians. Her principles governed all aspects of society, from legal proceedings and administrative decisions to personal conduct and moral behavior. The Egyptians believed that by living in accordance with Ma'at, they could ensure harmony and prosperity for themselves and their communities.
The iconography of Ma'at is rich with symbolism. The ostrich feather, her primary symbol, represents truth, lightness, and balance. It was often worn by pharaohs and officials as a sign of their commitment to justice and ethical conduct. Ma'at is also frequently depicted holding a scepter and an ankh, symbols of authority and life, further emphasizing her role as the guarantor of cosmic and social order.
Ma'at's legacy is evident in the numerous texts, monuments, and artistic representations that celebrate her. The "Instruction of Ptahhotep," one of the oldest known texts on ethics and morality, emphasizes the importance of living in accordance with Ma'at's principles. This text, along with others like the "Book of the Dead" and the "Pyramid Texts," highlights the enduring significance of Ma'at in shaping the moral and ethical framework of ancient Egyptian society.
In summary, Ma'at's mythology and worship underscore the ancient Egyptians' profound commitment to truth, justice, and balance. Her role as the personification of cosmic order and ethical conduct reflects the civilization's understanding of the interconnectedness of the universe and the importance of living a virtuous life. Ma'at's enduring legacy continues to influence modern interpretations of Egyptian mythology and ethical thought.
"""
        case 8:
            contentView.centerImage.image = .imgGodsNine
            contentView.bodyFieldInfo.text  = """
Hathor, one of the most beloved and multifaceted goddesses in ancient Egyptian mythology, is revered as the goddess of love, beauty, music, motherhood, and joy. Often depicted as a woman with cow horns and a solar disk or as a cow, Hathor embodies the nurturing and life-giving aspects of femininity. Her mythology and worship highlight the ancient Egyptians' appreciation for the pleasures of life, the arts, and maternal care.
Hathor's origins are ancient, dating back to the early periods of Egyptian history. She was initially worshipped as a cow goddess, symbolizing fertility and the abundance of nature. Over time, Hathor's attributes expanded, and she became associated with various aspects of life and the afterlife. Her connection to the sky and the sun is reflected in her epithet "Mistress of the West," where she was believed to welcome the souls of the deceased into the afterlife.
One of the central myths of Hathor is her role in the "Distant Goddess" narrative. According to this myth, Hathor, in her form as the lioness goddess Sekhmet, was sent by Ra to punish humanity for their sins. However, her rampage threatened to destroy all life. To stop her, Ra devised a plan to intoxicate her by dyeing beer to resemble blood. Hathor drank the beer, became intoxicated, and transformed back into her gentle and nurturing form, thus saving humanity. This myth underscores Hathor's dual nature as both a fierce protector and a benevolent mother.
Hathor's role as the goddess of music and dance is celebrated in numerous festivals and rituals. The "Festival of Drunkenness," held annually, commemorated her pacification and transformation back into her nurturing form. During this festival, participants engaged in music, dance, and intoxication, reflecting Hathor's joyous and life-affirming aspects. She was also revered as the patroness of miners and associated with the turquoise mines in Sinai, known as the "Mistress of Turquoise."
Hathor's association with motherhood and fertility is evident in her role as the "Great Mother" who nurtures and protects all living beings. She was often invoked by women seeking fertility, safe childbirth, and maternal protection. Hathor's nurturing nature is symbolized by the image of her suckling Horus, emphasizing her role as a mother to both gods and humans.
The worship of Hathor was widespread, with major cult centers at Dendera and other significant sites throughout Egypt. Her temples, such as the Temple of Hathor at Dendera, were centers of pilgrimage and devotion, where rituals and ceremonies were conducted to honor her and seek her blessings. The "Dendera Zodiac," a famous astronomical ceiling in her temple, reflects her connection to the sky and the cosmic order.
Hathor's influence extended beyond Egypt, impacting other cultures and religions. In Greek mythology, she was identified with Aphrodite, the goddess of love and beauty. Her attributes of music, dance, and joy were celebrated in various Mediterranean cultures, highlighting her universal appeal as a goddess of pleasure and creativity.
Hathor's iconography is rich and varied, reflecting her multifaceted nature. The cow, her sacred animal, symbolizes fertility, abundance, and maternal care. The sistrum, a musical instrument associated with Hathor, represents her role in music and dance. The solar disk and cow horns emphasize her connection to the sky and the sun, underscoring her role as a life-giver and protector.
In summary, Hathor's mythology and worship highlight the ancient Egyptians' appreciation for love, beauty, music, and maternal care. Her role as a nurturing and life-giving goddess reflects the civilization's values of joy, creativity, and the importance of family and community. Hathor's enduring legacy continues to influence modern interpretations of Egyptian mythology and cultural practices.
"""
        case 9:
            contentView.centerImage.image = .imgGodsTen
            contentView.bodyFieldInfo.text  = """
 Bastet, also known as Bast, is one of the most beloved and iconic goddesses in ancient Egyptian mythology. Revered as the goddess of home, fertility, childbirth, and cats, Bastet embodies the protective and nurturing aspects of femininity. Often depicted as a lioness or a woman with the head of a lioness or domestic cat, Bastet's mythology and worship highlight the ancient Egyptians' deep appreciation for domestic life, motherhood, and feline grace.
Bastet's origins are ancient, dating back to the Old Kingdom, where she was initially worshipped as a lioness goddess associated with protection and warfare. Over time, her attributes evolved, and she became more closely associated with the domestic cat, symbolizing gentleness, fertility, and the protection of the home. This transformation reflects the dual nature of Bastet as both a fierce protector and a nurturing mother.
One of the central myths of Bastet is her role as the "Eye of Ra," a powerful and vengeful aspect of the sun god Ra. According to this myth, Ra sent Bastet, in her lioness form, to punish his enemies and protect his followers. However, Bastet's wrath was tempered by her nurturing and protective qualities, symbolized by her transformation into the gentle and affectionate domestic cat. This duality underscores Bastet's role as a goddess who embodies both the protective and nurturing aspects of motherhood.
Bastet's role as the goddess of home and fertility is celebrated in numerous rituals and festivals. The "Feast of Bubastis," held annually in her honor, was one of the most popular and joyous festivals in ancient Egypt. During this festival, participants engaged in music, dance, and processions, reflecting Bastet's association with pleasure, celebration, and community. Bubastis, her primary cult center, was located in the Nile Delta and was renowned for its grand temple and vibrant festivities.
Bastet's association with cats is one of her most enduring and beloved attributes. The ancient Egyptians revered cats for their grace, agility, and ability to protect homes from vermin. As the goddess of cats, Bastet was believed to offer protection and blessings to those who cared for and respected these animals. Cats were often kept as pets and were sometimes mummified and buried with their owners as a sign of devotion to Bastet.
The worship of Bastet was widespread, with temples and shrines dedicated to her throughout Egypt. Her priests and priestesses played a vital role in maintaining her cult, conducting rituals and ceremonies to honor her and seek her protection. Amulets and statues of Bastet, often depicted as a cat or lioness, were commonly worn or placed in homes to invoke her blessings and ward off evil spirits.
Bastet's influence extended beyond Egypt, impacting other cultures and mythologies. In Greek mythology, she was identified with Artemis, the goddess of the hunt and protector of women. This syncretism highlights the universal appeal of Bastet's attributes of protection, motherhood, and grace.
Bastet's iconography is rich with symbolism. The cat, her sacred animal, represents grace, agility, and the protective spirit of the home. The lioness, another of her forms, symbolizes strength, courage, and the fierce protection of her followers. Bastet is often depicted holding a sistrum, a musical instrument associated with joy and celebration, emphasizing her connection to music and dance.
In summary, Bastet's mythology and worship highlight the ancient Egyptians' deep appreciation for domestic life, motherhood, and feline grace. Her role as a nurturing and protective goddess reflects the civilization's values of family, community, and the importance of caring for and respecting animals. Bastet's enduring legacy continues to influence modern interpretations of Egyptian mythology and cultural practices.
"""
        default:
            break

        }
    }
}
